minetest.register_node('masonry:quartz_pillar', {
   description = 'Quartz Pillar',
   tiles = {'masonry_quartz_pillar_top.png', 'masonry_quartz_pillar_top.png','masonry_quartz_pillar_side.png'},
   paramtype2 = 'facedir',
   on_place = minetest.rotate_node,
   sounds = default.node_sound_stone_defaults(),
   groups = {cracky=3}
})

minetest.register_node('masonry:quartz_pillar_stair', {
   description = 'Quartz Pillar',
   drawtype = "nodebox",
   tiles = {'masonry_quartz_pillar_top.png', 'masonry_quartz_pillar_side.png'},
   paramtype2 = 'facedir',
   on_place = minetest.rotate_node,
   sounds = default.node_sound_stone_defaults(),
   groups = {cracky=3},
   node_box = {
         type = "fixed",
         fixed = {
            {-0.5, -0.5, -0.5, 0.5, 0.0, 0.5},
            {-0.5, 0.0, 0.0, 0.5, 0.5, 0.5},
         },
      },
})

minetest.register_node('masonry:quartz_pillar_slab', {
   description = 'Quartz Pillar',
   drawtype = "nodebox",
   tiles = {'masonry_quartz_pillar_top.png', 'masonry_quartz_pillar_top.png','masonry_quartz_pillar_side.png'},
   paramtype2 = 'facedir',
   on_place = minetest.rotate_node,
   sounds = default.node_sound_stone_defaults(),
   groups = {cracky=3},
   node_box = {
         type = "fixed",
         fixed = {
            {-0.5, -0.5, -0.5, 0.5, 0.0, 0.5},
         },
      },
})

minetest.register_node('masonry:quartz_pillar_inner_stair', {
   description = 'Quartz Pillar',
   drawtype = "nodebox",
   tiles = {'masonry_quartz_pillar_top.png', 'masonry_quartz_pillar_top.png','masonry_quartz_pillar_side.png'},
   paramtype2 = 'facedir',
   on_place = minetest.rotate_node,
   sounds = default.node_sound_stone_defaults(),
   groups = {cracky=3},
   node_box = {
      type = "fixed",
      fixed = {
         {-0.5, -0.5, -0.5, 0.5, 0.0, 0.5},
         {-0.5, 0.0, 0.0, 0.5, 0.5, 0.5},
         {-0.5, 0.0, -0.5, 0.0, 0.5, 0.0},
      },
   },
})

minetest.register_node('masonry:quartz_pillar_outer_stair', {
   description = 'Quartz Pillar',
   drawtype = "nodebox",
   tiles = {'masonry_quartz_pillar_top.png', 'masonry_quartz_pillar_top.png','masonry_quartz_pillar_side.png'},
   paramtype2 = 'facedir',
   on_place = minetest.rotate_node,
   sounds = default.node_sound_stone_defaults(),
   groups = {cracky=3},
   node_box = {
      type = "fixed",
      fixed = {
         {-0.5, -0.5, -0.5, 0.5, 0.0, 0.5},
         {-0.5, 0.0, 0.0, 0.0, 0.5, 0.5},
      },
   },
})

stairs.register_stair_and_slab(
	"quartz_pillar",
	"masonry:quartz_pillar",
	{cracky = 3},
	{'masonry_quartz_pillar_top.png', 'masonry_quartz_pillar_side.png'},
	"Quartz Pillar Stair",
	"Quartz Pillar Slab",
	default.node_sound_stone_defaults(),
	false
)
